//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblEventRegistrations = new HashSet<tblEventRegistration>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> DateOfEvent { get; set; }
        public string Details { get; set; }
        public Nullable<int> ImageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEventRegistration> tblEventRegistrations { get; set; }
        public virtual tblUploadedImage tblUploadedImage { get; set; }
    }
}
