//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventRegistration
    {
        public int RegistrationID { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> EventID { get; set; }
    
        public virtual tblEvent tblEvent { get; set; }
    }
}
